import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'

const CHANGELOG =
  'https://github.com/DigiMonk73/BTCTX-MCP/blob/main/docs/CHANGELOG.md'

/** 1.2.5:0: the 2026 draft forms preview, the redesigned Complete Tax Report, the phone close button, locked dependencies; nothing for the package to migrate. */
export const current = VersionInfo.of({
  version: '1.2.5:0',
  releaseNotes: {
    en_US: `BitcoinTX 1.2.5 brings a preview of the 2026 tax forms. Until the IRS publishes the final ones, Reports offers 2026 filled in on the IRS's draft Form 8949 and Schedule D, marked "DRAFT — DO NOT FILE" on every page: use them to check your figures, never to file. The preview ends by itself at the end of 2026; the final forms come in an update. On a phone, the panel for adding or editing a transaction now has a close button (✕). The Complete Tax Report is redesigned, with the same figures: a cover with the year's key figures, a one-page summary showing each Form 8949 box with its Schedule D line, and clearer tables with totals; its almost always empty "Expenses" section is gone. Reports also offers the Transaction History as a PDF (choose the format), now fitting the page. Every component BitcoinTX is built from is now locked to an exact, verified version. Connect an AI Assistant shows the root CA certificate and the Claude Desktop configuration with their line breaks, and offers the certificate as a download. Price Source & Privacy explains what each price source does. Coming from 1.2.4:0 or earlier? Set Login Credentials replaces Show Credentials and Reset Login Credentials: it makes a new password and shows it once. Your login stays; only if StartOS keeps no password for you, stop BitcoinTX and run Set Login Credentials before starting it again; it replaces any username and password you set inside BitcoinTX. Coming from 1.2.1 or earlier? After updating, open Settings > Ledger Review in BitcoinTX, and if it lists figures a recalculation would change, run Recalculate Ledger. Everything: ${CHANGELOG}`,
    es_ES: `BitcoinTX 1.2.5 trae una vista previa de los formularios fiscales de 2026. Hasta que el IRS publique los definitivos, Reports ofrece 2026 rellenado en los borradores del IRS del Form 8949 y del Schedule D, marcados con "DRAFT — DO NOT FILE" en cada página: úsalos para revisar tus cifras, nunca para presentarlos. La vista previa termina sola a finales de 2026; los formularios definitivos llegan en una actualización. En un teléfono, el panel para añadir o editar una transacción tiene ahora un botón de cierre (✕). El Complete Tax Report se ha rediseñado, con las mismas cifras: una portada con las cifras clave del año, un resumen de una página con cada casilla del Form 8949 y su línea del Schedule D, y tablas más claras con totales; desaparece su sección "Expenses", casi siempre vacía. Reports también ofrece Transaction History en PDF (elige el formato), que ahora cabe en la página. Cada componente con el que se construye BitcoinTX está ahora fijado a una versión exacta y verificada. Conectar un asistente de IA muestra el certificado de la CA raíz y la configuración de Claude Desktop con sus saltos de línea, y ofrece el certificado como descarga. Fuente de precios y privacidad explica qué hace cada fuente de precios. ¿Vienes de la 1.2.4:0 o anterior? Establecer credenciales de acceso sustituye a Mostrar credenciales y Restablecer credenciales de acceso: genera una contraseña nueva y la muestra una sola vez. Tu acceso se conserva; solo si StartOS no guarda ninguna contraseña tuya, detén BitcoinTX y ejecuta Establecer credenciales de acceso antes de volver a iniciarlo; sustituye cualquier usuario y contraseña que hayas establecido dentro de BitcoinTX. ¿Vienes de la 1.2.1 o anterior? Tras actualizar, abre Settings > Ledger Review en BitcoinTX y, si muestra cifras que un recálculo cambiaría, ejecuta Recalcular el libro contable. Todo: ${CHANGELOG}`,
    de_DE: `BitcoinTX 1.2.5 bringt eine Vorschau der Steuerformulare für 2026. Bis der IRS die endgültigen veröffentlicht, bietet Reports 2026 an, ausgefüllt auf den Entwürfen des IRS für Form 8949 und Schedule D, auf jeder Seite mit "DRAFT — DO NOT FILE" markiert: Nutze sie, um deine Zahlen zu prüfen, niemals zur Abgabe. Die Vorschau endet von selbst Ende 2026; die endgültigen Formulare kommen mit einem Update. Auf dem Handy hat das Feld zum Hinzufügen oder Bearbeiten einer Transaktion jetzt eine Schließen-Schaltfläche (✕). Der Complete Tax Report ist neu gestaltet, mit denselben Zahlen: ein Deckblatt mit den wichtigsten Zahlen des Jahres, eine einseitige Übersicht mit jedem Feld des Form 8949 und seiner Zeile im Schedule D sowie übersichtlichere Tabellen mit Summen; der fast immer leere Abschnitt "Expenses" entfällt. Reports bietet die Transaction History jetzt auch als PDF an (Format wählen), das auf die Seite passt. Jeder Baustein, aus dem BitcoinTX gebaut wird, ist jetzt auf eine genaue, geprüfte Version festgelegt. KI-Assistenten verbinden zeigt das Root-CA-Zertifikat und die Claude-Desktop-Konfiguration mit ihren Zeilenumbrüchen und bietet das Zertifikat zum Herunterladen an. Kursquelle & Datenschutz erklärt, was jede Kursquelle tut. Du kommst von 1.2.4:0 oder älter? Zugangsdaten festlegen ersetzt Zugangsdaten anzeigen und Zugangsdaten zurücksetzen: Die Aktion erzeugt ein neues Passwort und zeigt es einmalig. Deine Zugangsdaten bleiben; nur wenn StartOS kein Passwort für dich gespeichert hat, stoppe BitcoinTX und führe Zugangsdaten festlegen vor dem nächsten Start aus; die Aktion ersetzt Benutzernamen und Passwort, die du in BitcoinTX selbst gesetzt hast. Du kommst von 1.2.1 oder älter? Öffne nach dem Update Settings > Ledger Review in BitcoinTX, und listet es Zahlen, die eine Neuberechnung ändern würde, führe Journal neu berechnen aus. Alles: ${CHANGELOG}`,
    pl_PL: `BitcoinTX 1.2.5 przynosi podgląd formularzy podatkowych na 2026 rok. Dopóki IRS nie opublikuje ostatecznych, Reports oferuje rok 2026 wypełniony na projektach IRS formularzy Form 8949 i Schedule D, oznaczonych na każdej stronie "DRAFT — DO NOT FILE": używaj ich do sprawdzenia swoich wartości, nigdy do złożenia. Podgląd kończy się sam z końcem 2026 roku; ostateczne formularze przyjdą w aktualizacji. Na telefonie panel dodawania lub edycji transakcji ma teraz przycisk zamknięcia (✕). Complete Tax Report ma nowy wygląd, z tymi samymi wartościami: stronę tytułową z kluczowymi wartościami roku, jednostronicowe podsumowanie z każdym polem Form 8949 i jego wierszem w Schedule D oraz czytelniejsze tabele z sumami; znika prawie zawsze pusta sekcja "Expenses". Reports oferuje też Transaction History jako PDF (wybierz format), który mieści się teraz na stronie. Każdy składnik, z którego budowany jest BitcoinTX, jest teraz przypięty do dokładnej, zweryfikowanej wersji. Połącz asystenta AI pokazuje certyfikat głównego CA i konfigurację Claude Desktop z podziałem na wiersze oraz oferuje certyfikat do pobrania. Źródło cen i prywatność wyjaśnia, co robi każde źródło cen. Aktualizujesz z 1.2.4:0 lub starszej wersji? Ustaw dane logowania zastępuje Pokaż dane logowania i Zresetuj dane logowania: generuje nowe hasło i pokazuje je tylko raz. Twoje dane logowania zostają; tylko jeśli StartOS nie przechowuje dla ciebie hasła, zatrzymaj BitcoinTX i uruchom Ustaw dane logowania przed ponownym uruchomieniem; akcja zastępuje każdą nazwę użytkownika i hasło ustawione w samym BitcoinTX. Aktualizujesz z 1.2.1 lub starszej wersji? Po aktualizacji otwórz Settings > Ledger Review w BitcoinTX, a jeśli pokazuje wartości, które zmieniłoby przeliczenie, uruchom Przelicz księgę. Wszystko: ${CHANGELOG}`,
    fr_FR: `BitcoinTX 1.2.5 apporte un aperçu des formulaires fiscaux de 2026. En attendant que l’IRS publie les versions définitives, Reports propose 2026 rempli sur les projets de l’IRS du Form 8949 et du Schedule D, marqués « DRAFT — DO NOT FILE » sur chaque page : servez-vous-en pour vérifier vos chiffres, jamais pour les déposer. L’aperçu s’arrête de lui-même à la fin de 2026 ; les formulaires définitifs arrivent dans une mise à jour. Sur un téléphone, le panneau d’ajout ou de modification d’une transaction a maintenant un bouton de fermeture (✕). Le Complete Tax Report est entièrement repensé, avec les mêmes chiffres : une page de garde avec les chiffres clés de l’année, un résumé d’une page présentant chaque case du Form 8949 avec sa ligne du Schedule D, et des tableaux plus clairs avec leurs totaux ; sa section « Expenses », presque toujours vide, disparaît. Reports propose aussi Transaction History en PDF (choisissez le format), qui tient désormais dans la page. Chaque composant à partir duquel BitcoinTX est construit est désormais fixé à une version exacte et vérifiée. Connecter un assistant IA affiche le certificat de l’AC racine et la configuration Claude Desktop avec leurs retours à la ligne, et propose le certificat en téléchargement. Source des prix et confidentialité explique ce que fait chaque source de prix. Vous venez de la 1.2.4:0 ou d’une version antérieure ? Définir les identifiants remplace Afficher les identifiants et Réinitialiser les identifiants : cette action génère un nouveau mot de passe et l’affiche une seule fois. Vos identifiants sont conservés ; seulement si StartOS ne garde aucun mot de passe pour vous, arrêtez BitcoinTX et lancez Définir les identifiants avant de le redémarrer ; cette action remplace tout nom d’utilisateur et mot de passe définis dans BitcoinTX lui-même. Vous venez de la 1.2.1 ou d’une version antérieure ? Après la mise à jour, ouvrez Settings > Ledger Review dans BitcoinTX et, s’il liste des chiffres qu’un recalcul changerait, lancez Recalculer le registre. Tout : ${CHANGELOG}`,
  },
  migrations: {
    up: async () => {},
    down: IMPOSSIBLE,
  },
})
