import { IMPOSSIBLE, VersionInfo } from '@start9labs/start-sdk'
import { sdk } from '../sdk'

const CHANGELOG =
  'https://github.com/DigiMonk73/BTCTX-MCP/blob/main/docs/CHANGELOG.md'

/**
 * 1.2.4:1 (Start9's review): Set Login Credentials replaced Show Credentials
 * and Reset Login Credentials; the migration clears a leftover Show
 * Credentials task.
 */
export const v_1_2_4_1 = VersionInfo.of({
  version: '1.2.4:1',
  releaseNotes: {
    en_US: `Package revision 1: Set Login Credentials replaces Show Credentials and Reset Login Credentials. It generates and shows a new password once, and also resets a lost login. Existing generated logins are kept; if your older install has no password stored by StartOS, stop BitcoinTX and run Set Login Credentials before starting it again. Retired Show Credentials tasks are cleared. BitcoinTX 1.2.4 brings small fixes found by testing 1.2.3, with no change to any tax figure. A CSV export imported again now keeps a fee of 0 as 0 instead of dropping it. On a phone, every tab in the top bar fits on screen, Logout included. Escape closes the panel for adding or editing a transaction, asking first if you have unsaved changes. An unused transaction lock that nothing could switch on was removed; this updates the database once (a copy of it is kept first). Coming from 1.2.1 or earlier? You also get 1.2.2's tax-figure fixes and 1.2.3's code cleanup: after updating, open Settings > Ledger Review in BitcoinTX, and if it lists figures a recalculation would change, run Recalculate Ledger. Everything: ${CHANGELOG}`,
    es_ES: `Revisión 1 del paquete: Establecer credenciales de acceso sustituye a Mostrar credenciales y Restablecer credenciales de acceso. Genera y muestra una contraseña nueva una sola vez y también permite recuperar el acceso. Se conservan los accesos generados existentes; si tu instalación antigua no tiene una contraseña guardada por StartOS, detén BitcoinTX y ejecuta Establecer credenciales de acceso antes de volver a iniciarlo. Se eliminan las tareas antiguas de Mostrar credenciales. BitcoinTX 1.2.4 trae pequeñas correcciones encontradas al probar la 1.2.3, sin cambiar ninguna cifra fiscal. Un CSV exportado e importado de nuevo ahora conserva una comisión de 0 como 0 en lugar de eliminarla. En un teléfono, todas las pestañas de la barra superior caben en la pantalla, incluido Logout. La tecla Escape cierra el panel para añadir o editar una transacción, preguntando antes si tienes cambios sin guardar. Se eliminó un bloqueo de transacciones sin uso que nada podía activar; esto actualiza la base de datos una vez (antes se guarda una copia). ¿Vienes de la 1.2.1 o anterior? También recibes las correcciones de cifras fiscales de la 1.2.2 y la reorganización del código de la 1.2.3: tras actualizar, abre Settings > Ledger Review en BitcoinTX y, si muestra cifras que un recálculo cambiaría, ejecuta Recalcular el libro contable. Todo: ${CHANGELOG}`,
    de_DE: `Paketrevision 1: Zugangsdaten festlegen ersetzt Zugangsdaten anzeigen und Zugangsdaten zurücksetzen. Die Aktion erzeugt und zeigt ein neues Passwort einmalig und hilft auch bei verlorenen Zugangsdaten. Bereits generierte Zugangsdaten bleiben erhalten; hat eine ältere Installation kein von StartOS gespeichertes Passwort, stoppe BitcoinTX und führe Zugangsdaten festlegen vor dem nächsten Start aus. Alte Aufgaben für Zugangsdaten anzeigen werden entfernt. BitcoinTX 1.2.4 bringt kleine Korrekturen aus den Tests von 1.2.3, ohne eine Steuerzahl zu ändern. Eine exportierte und wieder importierte CSV behält eine Gebühr von 0 jetzt als 0, statt sie wegzulassen. Auf dem Handy passen alle Reiter der oberen Leiste auf den Bildschirm, Logout eingeschlossen. Die Escape-Taste schließt das Feld zum Hinzufügen oder Bearbeiten einer Transaktion und fragt vorher, wenn du ungespeicherte Änderungen hast. Eine ungenutzte Sperre für Transaktionen, die nichts einschalten konnte, wurde entfernt; dafür wird die Datenbank einmal aktualisiert (vorher wird eine Kopie gesichert). Du kommst von 1.2.1 oder älter? Dann erhältst du auch die Korrekturen der Steuerzahlen aus 1.2.2 und die Code-Neuordnung aus 1.2.3: Öffne nach dem Update Settings > Ledger Review in BitcoinTX, und listet es Zahlen, die eine Neuberechnung ändern würde, führe Journal neu berechnen aus. Alles: ${CHANGELOG}`,
    pl_PL: `Rewizja pakietu 1: Ustaw dane logowania zastępuje Pokaż dane logowania i Zresetuj dane logowania. Generuje nowe hasło i pokazuje je tylko raz, a także pozwala odzyskać dostęp. Istniejące wygenerowane dane logowania zostają zachowane; jeśli starsza instalacja nie ma hasła zapisanego przez StartOS, zatrzymaj BitcoinTX i uruchom Ustaw dane logowania przed ponownym uruchomieniem usługi. Stare zadania Pokaż dane logowania są usuwane. BitcoinTX 1.2.4 przynosi drobne poprawki znalezione podczas testów 1.2.3, bez zmiany żadnej wartości podatkowej. Wyeksportowany i ponownie zaimportowany plik CSV zachowuje teraz opłatę 0 jako 0, zamiast ją pomijać. Na telefonie wszystkie karty górnego paska mieszczą się na ekranie, łącznie z Logout. Klawisz Escape zamyka panel dodawania lub edycji transakcji, a jeśli masz niezapisane zmiany, najpierw pyta. Usunięto nieużywaną blokadę transakcji, której nic nie mogło włączyć; wymaga to jednorazowej aktualizacji bazy danych (wcześniej zapisywana jest jej kopia). Aktualizujesz z 1.2.1 lub starszej wersji? Otrzymujesz też poprawki wartości podatkowych z 1.2.2 i uporządkowanie kodu z 1.2.3: po aktualizacji otwórz Settings > Ledger Review w BitcoinTX, a jeśli pokazuje wartości, które zmieniłoby przeliczenie, uruchom Przelicz księgę. Wszystko: ${CHANGELOG}`,
    fr_FR: `Révision 1 du paquet : Définir les identifiants remplace Afficher les identifiants et Réinitialiser les identifiants. Cette action génère et affiche un nouveau mot de passe une seule fois et permet aussi de récupérer l’accès. Les identifiants déjà générés sont conservés ; si votre ancienne installation n’a aucun mot de passe enregistré par StartOS, arrêtez BitcoinTX et lancez Définir les identifiants avant de le redémarrer. Les anciennes tâches Afficher les identifiants sont supprimées. BitcoinTX 1.2.4 apporte de petites corrections trouvées en testant la 1.2.3, sans changer aucun chiffre fiscal. Un CSV exporté puis réimporté conserve désormais des frais de 0 comme 0 au lieu de les supprimer. Sur un téléphone, tous les onglets de la barre du haut tiennent à l’écran, Logout compris. La touche Échap ferme le panneau d’ajout ou de modification d’une transaction, en demandant d’abord si vous avez des modifications non enregistrées. Un verrou de transaction inutilisé, que rien ne pouvait activer, a été retiré ; la base de données est mise à jour une fois pour cela (une copie en est gardée avant). Vous venez de la 1.2.1 ou d’une version antérieure ? Vous recevez aussi les corrections de chiffres fiscaux de la 1.2.2 et la réorganisation du code de la 1.2.3 : après la mise à jour, ouvrez Settings > Ledger Review dans BitcoinTX et, s’il liste des chiffres qu’un recalcul changerait, lancez Recalculer le registre. Tout : ${CHANGELOG}`,
  },
  migrations: {
    up: async ({ effects }) => {
      await sdk.action.clearTask(effects, 'btctx:show-credentials')
    },
    down: IMPOSSIBLE,
  },
})
